### ISSUE TITLE
Nov 25: Reschedule 

### ISSUE THREAD

**Issue by saihaj** [graphql/graphql-js-wg#18]
Me and @gagoar joined today at UTC 4PM waited for 15 minutes and no one showed up. Are we planning to have a meeting this week? Is there a meeting next month?
- assignee(s):  @IvanGoncharov @Urigo 
- source: 

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by Urigo** [comment]
I was also there I think, maybe on the wrong link.....

But I think @IvanGoncharov should be there otherwise there is less point of the meeting
cc @IvanGoncharov, are you able to join, or will you reschedule for another time?

**Comment by saihaj** [comment]
Is the link for graphql-wg same as this or different?

**Comment by IvanGoncharov** [comment]
@Urigo @saihaj Sorry confused time with graphql-wg so I thought it one-hour later.
How about in UTC 5PM?

**Comment by Urigo** [comment]
I'm not sure I can stay that late, maybe just the start, but I'm not a must, I think to sync and unblock @saihaj and @gagoar 's work on TS migrations is the most important

**Comment by saihaj** [comment]
What is the plan for next month? I forgot to bring it up in the meeting. Is it going to be on 30th December 1700 UTC?
