### ISSUE TITLE
Move December call to early January

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphql-js-wg#20]
Can we move the December call to Jan 5th same time?
What do you think?

cc: @Urigo @saihaj @robrichard @onhate @gagoar 

P.S. Sorry for the last-minute change should be posted earlier.

**Comment by saihaj** [comment]
Works for me. Will it be 4pm UTC or 5pm UTC last time there was a little bit of confusion?

**Comment by gagoar** [comment]
sounds good to me! maybe a calendar invite would work best for attending on
time cross time zones?
Gago
Linux User #484680
http://scr.im/gagoar
echo  xAeroMicPe@gSmPaMil.com | sed 's/[SPAM]//g'
