### ISSUE TITLE
[2021-01-27]: Fix google calendar and iCal links

### ISSUE THREAD

**Issue by saihaj** [graphql/graphql-js-wg#24]
currently the subscribe links subscribe to GraphiQL working group.
- assignee(s):  @IvanGoncharov 
- source: 

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by Sytten** [comment]
Can you add them to general WG calendar?

**Comment by brianwarner** [comment]
I've just merged the updated calendar info, and added the working group meetings to the general [calendar](https://calendar.graphql.org), and also added a unique Zoom link for this working group. Should hopefully take care of things.
