### ISSUE TITLE
Moving WG call to the March 3th

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphql-js-wg#31]
Hi guys,

Have a nasty fever 🤒 (just did COVID test today) not sure if I would be able to join on Wednesday.
Can we move the call to March 3th?

cc: @Urigo @saihaj @robrichard @onhate @kamilkisiela

**Comment by saihaj** [comment]
Is it possible if we can move this one hour early (4 PM UTC) on March 3rd?

**Comment by Urigo** [comment]
@IvanGoncharov sounds good to me! also, until the meeting, would you mind commenting here with a short sentence about the current state of the TS efforts since the last meeting?

Hope you feel better soon, sending love and hopes!

**Comment by IvanGoncharov** [comment]
@Urigo 
* released [15.5.0](https://github.com/graphql/graphql-js/releases/tag/v15.5.0) and branch out `15.x.x`
* merged `16.x.x` into `main`
* remove last polyfills and finished all planned breaking changes (still have to do a few unplanned ones discovered during TS conversion) so ~90% ready for `16.0.0-rc1`.
* @saihaj rebased his PR on `master` and incorporated @kamilkisiela changes split up into reviewable commits: https://github.com/graphql/graphql-js/pull/2828/commits

P.S. Have a nasty version of COVID but hopefully will fill better by March 3th.

**Comment by Urigo** [comment]
@IvanGoncharov OMG I'm so sorry to hear!  please focus on yourself, if we'll miss this meeting nothing will happen, focus on your health!

**Comment by IvanGoncharov** [comment]
Hi @Urigo @saihaj @robrichard @onhate @kamilkisiela

Sorry, can't join the call today((
Have small pneumonia and cough but overall feel better, today my first day without a fever 🎉
