### ISSUE TITLE
Move July meeting to Aug 4th

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphql-js-wg#46]
I spend last month going through various job interviews and it was a pretty exhausting process for me.
I gave myself some time off but now I'm back and ready to review PRs and cut the 16.0.0 release.

Since not a lot of progress is done since the last meeting and we also have empty agenda.
Let's move a call to next Wednesday, Aug 4th that way we can discuss what is left for the 16.0.0 release.

@robrichard @saihaj @yaacovCR What do you think about this proposal?

**Comment by saihaj** [comment]
Sounds good 👍🏼 I will update the agenda
