### ISSUE TITLE
Planned release schedule / LTS

### ISSUE THREAD

**Issue by saihaj** [graphql/graphql-js-wg#51]
We started working on `v16` long ago and still haven't delivered it. We discuss each time in WG but fall short on our deadlines all the time. Moving forward from this release we really need to setup a plan a schedule for a releases. We should plan out the breaking changes for at least 2 releases. It is an iterative process so will be pushing new features and fixing bugs  so we shouldn't hold back for too long. Once we have all the planned breaking changes we should cut a release and yes we need to automate our deployment pipelines.

**Comment by IvanGoncharov** [comment]
Branch out the issue about canary released here https://github.com/graphql/graphql-js/issues/3383

**Comment by benjie** [comment]
Closing this since V16 has shipped
