### ISSUE TITLE
[2020-09-16] Promote Marcelo in triaging permissions role

### ISSUE THREAD

**Issue by Urigo** [graphql/graphql-js-wg#6]
Promote Marcelo in triaging permissions role

- assignee(s): @IvanGoncharov
- source: https://github.com/graphql/graphql-js-wg/blob/main/notes/2020-09-16.md#other-things
-------------------------------------------------------------------------------------
_Note: Action Item issues are reviewed and closed during Working Group meetings._

**Comment by IvanGoncharov** [comment]
Sent invitation need to check if accepted.
