### ISSUE TITLE
[2020-09-16] Create detailed issues and a public roadmap for everything that's needed for the Typescript migration

### ISSUE THREAD

**Issue by Urigo** [graphql/graphql-js-wg#7]
Create detailed issues and a public roadmap for everything that's needed from @IvanGoncharov point of view for the Typescript migration so all contributors could start the work

- assignee(s): @IvanGoncharov
- source: https://github.com/graphql/graphql-js-wg/blob/main/notes/2020-09-16.md#typescript-migration-plan-15m-uri
-------------------------------------------------------------------------------------
_Note: Action Item issues are reviewed and closed during Working Group meetings._

**Comment by IvanGoncharov** [comment]
Created here: https://github.com/graphql/graphql-js/issues/2860
