### ISSUE TITLE
Feb 23 WG Cancelled

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphql-js-wg#76]
I'm going through some medical issues (serious but not life-threatening) so I took this day off.
Since the agenda is packed let's move it to another date at the being of next month.
How about March 9th, will it work for you all?

cc: @saihaj @robrichard @yaacovCR @n1ru4l

P.S. If you have something that you want to discuss please free to use the Zoom link today and I will watch the recording to be in the loop.
Also, I will try to review open PRs in the next couple of days.

**Comment by n1ru4l** [comment]
take care and stay safe!

March 9th seems good to me!

**Comment by robrichard** [comment]
March 9th works for me too

**Comment by saihaj** [comment]
Take care! will cancel Today's meeting and move to March 9

**Comment by yaacovCR** [comment]
Feel good, that works
