### ISSUE TITLE
[2020-09-16] Create issues and project from all action items

### ISSUE THREAD

**Issue by Urigo** [graphql/graphql-js-wg#9]
@urigo should create and manage all issues, action items, projects and structures for the graphql-js public working group repo

- assignee(s): @urigo
- source: https://github.com/graphql/graphql-js-wg/blob/main/notes/2020-09-16.md#determine-volunteers-for-note-taking-1m-ivan
-------------------------------------------------------------------------------------
_Note: Action Item issues are reviewed and closed during Working Group meetings._

**Comment by IvanGoncharov** [comment]
@Urigo Thanks 🎉
