### ISSUE TITLE
Cancel meeting on Aug 31st 2022

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphql-js-wg#96]
Since there are no agenda items, let's cancel the meeting today (Aug 31st).

I want to discuss the roadmap for v17 and a few other issues, but I think it is more productive to open an issue on `graphql-js` repo and discuss it there first.

If someone has any issues they want to discuss in person, please add them to the next agenda, or if it is urgent, we can schedule a meeting even earlier (just suggest a date).

cc: @yaacovCR @saihaj

**Comment by saihaj** [comment]
sounds good!
